### ISSUE TITLE
Separate the worker, from a model worker.. maybe

### ISSUE THREAD

**Issue by zomble** [php-resque/resque#14]
Something that I'm finding difficult is the data model that represents a worker, and the actual worker process is the fact that they are the same object.

I'm thinking of something like `Resque\Component\Worker\Worker`. Which does the actual forking and so on. And `Resque\Component\Worker\Model\Worker` as the data object that represents a known worker.

And to construct a `Resque\Component\Worker\Worker` requires you pass it a `Resque\Component\Worker\Model\Worker` .

**Comment by splitice** [comment]
Perhaps a WorkerProcess that contains the main, and a "Worker" object that represents the worker regardless of its location (and can contain helper methods to find the process and get the WorkerProcess if located on the same machine)?

**Comment by zomble** [comment]
Good suggestion. I have been playing with a similar idea in a branch on my local. That strips everything from the current "Worker" class that has to do with the "state" of the worker.

Though I've renamed i tot "WorkerDeamon" instead of "WorkerProcess". I don't like Deamon now that I think about it. Cause it's not really one.

The Resque\Component\Worker\Model\WorkerInterface now just has getPid(), getCurrentJob(). getHostname(), getStartedAt() and other pure state representation things on it. Which means working with worker information is much simpler.

I'll push it up when I'm home for you to look at.
