### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by splitice** [php-resque/resque#16]
Can I make a request that once you are moderately happy (perhaps after worker changes) you do a pre-release version? It can be v0.1.0alpha1 for all that matters.

I would be happy to test it for you and report any issues. That makes it easier to easily identify releases to merge, QA and deploy.

**Comment by zomble** [comment]
Absolutely. It will be after this worker thing is resolved.

I appreciate your help dude.

It'll also help me with the bundle.
