### ISSUE TITLE
Desired behavior when a worker fails to pull a Job from a Queue, because of Redis comms

### ISSUE THREAD

**Issue by zomble** [php-resque/resque#2]
Currently if you fill the tcp connection pool or do some other silly thing, all workers will die due to connection exceptions from predis.

Is this okay? Or should I allow certain exceptions to not halt the worker loop?

**Comment by splitice** [comment]
What about catching the exception, handling as unhandled exception (logged warning), wait 30 seconds, restart worker process loop?
