### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by splitice** [php-resque/resque#4]
Recently I have been investigating the feasibility of moving from our internal dogs breakfeast of a Resque port (heavily based off your code back many revisions) to a more modern implementation. As part of this process I have been reviewing your current code base, trying to ascertain its state.

I am glad to see you are still working on this after 6mo, and am looking to donate some of my time to making the latest revisions ready. Specifically to help bring some of the features we have implemented out of need over to your fork.

Some of the features identified as missing (correct me if I am wrong):
 - Worker Restart on Unexpected Failure
 - Worker spawning with custom queue configurations (i.e Worker1: q1, q2 Worker2: q3). Ive integrated this currently by extending Application, although 
 - Working/Passing Tests. They exist, but there is a large number of ones with significant errors. I would love to see this working so I can work on this project free from fear of introducing regressions.

**Comment by zomble** [comment]
Hey Mathew,

Your reasons are the same reasons for my rewrite and my work towards componetising the code base.

I am still working on this, and it's on going as I fit it in between my day job and other projects i'm working on all. All of which use actually use the original php resque.

You are correct on the features there. I am also working towards disconnecting Redis from being core to the code. This helps with code quality.

I'm off to look at your other issues and PR now. Thanks for taking an interest!

**Comment by splitice** [comment]
I ended up getting worker restart, some changes made to support custom spawning & improved worker awareness of other workers. Oh and fixed some bugs (i.e missing classes).

Currently I am just extending the Application class and overriding protected methods for custom spawning. Not the cleanest solution, but its workable for now.

So far its running in production for a week without issues FYI.

I fully expect a request for some PHPDoc / comments in the PR. I really wanted to see if you where open to it / happy with the structure before putting more effort in.

**Comment by zomble** [comment]
That's actually awesome to hear!

Yeah, reading through the PR it does fix a lot of things, but it also cut some corners on things, none which I have issues fixing anyway!

To clarify is this PR you sent what you have running in prod at this point in time?

Also, I am actually curious what reason made you run with this particular fork, given it's state? haha.

**Comment by splitice** [comment]
Our existing resque fork was a mess, heavily based off yours (back when it worked, more or less) but with but I outsourced the development and it was done poorly (had one particularly hard to find bug).

Was easier to re-base and re-implement the required features. It didn't take much to fix this once I found the fork issue, and added a bit of logging that was missing.

I would call it less corner cutting, more like making changes that don't influence architecture. Methods, not classes.

Overall, re-based I doubt there is much to this patch. Primarily I left all the commits in the PR as the log is important to understanding reasons.

**Comment by zomble** [comment]
Ah, sorry for the hassle. I was still screwing around thinking about what the real goal was.

Cool.

Fair enough. As a side note I am perfectly happy for the architecture to be influenced for the better.

I'm not fused about rebasing, I prefer the history.

We'll continue this in the PR, and other issues!
